### ISSUE TITLE
MOBot Helper bug and qa

### ISSUE THREAD

**Issue by transfaeries** [mobilecoinofficial/forest#113]
here's some things I've found about Mobot whilst using it.

`What memo would you like to use? ('None' for empty` 

extra open paren

`Happy gifting!` 

but it was a payment request... confusing.

Taking pictures of QR codes doesn't always work, sometimes the bot things I want to save a picture for a template instead of finding a qr code. Annoyingly it scanned the code for a payment request (which helper can't fulfill) but it refuses to scan a gift code qr which only Helper can redeem. Very annoying.

**Comment by transfaeries** [comment]
signalme would be cooler if it could print the user a QR code for THEIR phone number instead of just a link for the bot.

**Comment by itdaniher** [comment]
mostly resolved in #111 

thanks faeries!

**Comment by technillogue** [comment]
@transfaeries does anything still need to be done about this?
