### ISSUE TITLE
Auxin should have path to get profile key if user doesn't message from primary device

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [mobilecoinofficial/forest#118]
* Auxin only knows it if there's a profile key if messaged from first bot
* A challenge needs to be sent from auxin or python bot head to get user to message from primary device

**Comment by technillogue** [comment]
see https://github.com/mobilecoinofficial/forest/commit/fbdd952808d9bd295da4c1e3a3b90e45f11b376a#diff-01eb77f63c3e388ea4367eb0cf393e451561e047511d77ea58b3086855ec9a76 for device id.

**Comment by technillogue** [comment]
device_id field in dataMessage on auxin
