### ISSUE TITLE
[docs] Note slow install command: curl signalcaptchas.org

### ISSUE THREAD

**Issue by dsernst** [mobilecoinofficial/forest#130]
While going through the README's install instructions, in the section [Registering a Signal Account for your bot](https://github.com/mobilecoinofficial/forest/#registering-a-signal-account-for-your-bot), running the line:

```bash
export CAPTCHA=$(curl -s --data-binary "https://signalcaptchas.org/registration/generate.html" https://human-after-all-21.fly.dev/6LedYI0UAAAAAMt8HLj4s-_2M_nYOhWMMFRGYHgY | jq -r .solution.gRecaptchaResponse)
```

seemed to hang. Unclear if it was broken or what.

After approx 60 seconds, it proceeded. 👍👍

Would be nice to note this in the install instructions. E.g.:

> The 2nd command will take a minute to complete.

**Comment by cxloe** [comment]
Made a quick edit to the readme with this, thanks!
