### ISSUE TITLE
ModuleNotFoundError using pdictng

### ISSUE THREAD

**Issue by deepfates** [mobilecoinofficial/forest#132]
Importing `aPersistDict` gives a dependency error:

`ModuleNotFoundError: No module named 'Crypto'`

This module should be installed with `pycryptodome` dependency which is already in the Pipfile. I reinstalled it with 

`pipenv install pycryptodome`

and this seemed to work. Don't understand why it wouldn't be installed with the original Pipfile though...

**Comment by itdaniher** [comment]
Probably because you updated and pycryptodome wasn't originally included in the Pipfile! Closing for now, but glad to have this as a reference point should future issues emerge.
