### ISSUE TITLE
what to call the payments demo.

### ISSUE THREAD

**Issue by transfaeries** [mobilecoinofficial/forest#139]
Making an issue so we can discuss it, keep track, and get ideas. 

The payments demo started life as a rewrite of echopay. The current rewrite so far does not actually implement echoing payments. It demonstrates the ability to send and receive payments, and react to sent and received payments. Without implementing echoing payments. 

That brings up a couple questions:
- Should we change the payments demo in some way to implement an echopay (I don't think it's necessary, but I'm open to discussion)
- What should we call the payments demo if not echopay.py

Part of the tutorial includes modifying the code and so I want to include before and after examples. So whatever naming convention we choose we also need two names. I've been using echopay.py and echopay_final.py but that could be confusing.

**Comment by cxloe** [comment]
Letting anyone run a faucet bot would be cool. Not really a big deal but would be nice to bring back the actual echopay bit.

Could just call it something like 'faucet.py' and 'payments.py', stick it in 'sample_bots/'...

**Comment by transfaeries** [comment]
yeah I was thinking it could just be a separate bot. I do want the payments demo to have its own dir so that it can hold both versions, plus what's required for Fly deployment. Since that will be part of the tutorial for this one. At least.... eventually. I haven't even deployed it to fly yet. 

so we could have an echopay.py that does echopay in samplebots. And maybe call the payments demo payments-demo and the files payments.py and payments_modified.py

**Comment by transfaeries** [comment]
we figured this one out
