### ISSUE TITLE
Unexpected behavior when sending reaction in groups

### ISSUE THREAD

**Issue by deepfates** [mobilecoinofficial/forest#177]
When using `self.send_reaction` in DMs, it seems to work normally. However, when in groups, only the target author can see the reaction that the bot puts on their post. This is not the behavior i experience as a user of Signal Android or Desktop. Not sure if this is a bug in the `Signal` class, or an `rpc` error, or something in the underlying `signal-cli`.

**Comment by technillogue** [comment]
this seems like it might be a bug with signal-cli, we should test `signal-cli sendReaction` directly w/o jsonrpc

**Comment by technillogue** [comment]
https://github.com/mobilecoinofficial/forest/blob/main/forest/core.py#L496

lol we only ever send it as a DM, clients just magically figure out what message it's actually reacting too...

**Comment by technillogue** [comment]
should be closed now
