### ISSUE TITLE
Repo Restructure

### ISSUE THREAD

**Issue by transfaeries** [mobilecoinofficial/forest#50]
Repo should be restructured. I have some ideas as to how this could be done.

We can have directories for sample bots, or each bot could have it's own directory.

Unfortunately restructuring the dir would mean rewriting some of the code. I think some ide's would do this for you. Maybe just Pycharm would do that. Anyone have pycharm?

I can submit a proposal for a potential organisation scheme. And we can make it happen.

**Comment by transfaeries** [comment]
Here is a sample repo, where I reorganised all the files and added READMEs

https://github.com/transfaeries/forest-restructure 

If we can get the repo to look like this, I think that would be a good organisation or materials.

**Comment by transfaeries** [comment]
Mostly resolved by

https://github.com/mobilecoinofficial/forest/pull/53 

Will leave open for now to track further restructuring if it happens in the near future.

**Comment by itdaniher** [comment]
closed by #62
