### ISSUE TITLE
logging and alerting on (critical) errors

### ISSUE THREAD

**Issue by itdaniher** [mobilecoinofficial/forest#8]
wondering if we can make a signal group and message it with tracebacks? :thinking: 

if we're not independently robust enough for that, we will need a basic mailbox / queue to catch and log failures.

smtp to a server we control might work, even submissions to a google form - simpler requests the better.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201632126650504/1201632377751899) by [Unito](https://www.unito.io)

**Comment by technillogue** [comment]
we more or less have this already from #31 , I think we should make a new issue if there's a specific error or log that's being inadequately handled
